// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWON6RODzGIGUDnYTlaR6M5cdy8mscDUo',
    appId: '1:938038236717:android:cde9e17fb3d539198b8aa4',
    messagingSenderId: '938038236717',
    projectId: 'playplugfox',
    storageBucket: 'playplugfox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl11pXXN62cwNuIVl7JYaoDryS5RdfZBM',
    appId: '1:938038236717:ios:5dc08152edbd1ccc8b8aa4',
    messagingSenderId: '938038236717',
    projectId: 'playplugfox',
    storageBucket: 'playplugfox.appspot.com',
    iosClientId: '938038236717-a4n6lr20d8ds9amaskm3p30reunnpkj4.apps.googleusercontent.com',
    iosBundleId: 'dev.plugfox.playground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl11pXXN62cwNuIVl7JYaoDryS5RdfZBM',
    appId: '1:938038236717:ios:5dc08152edbd1ccc8b8aa4',
    messagingSenderId: '938038236717',
    projectId: 'playplugfox',
    storageBucket: 'playplugfox.appspot.com',
    iosClientId: '938038236717-a4n6lr20d8ds9amaskm3p30reunnpkj4.apps.googleusercontent.com',
    iosBundleId: 'dev.plugfox.playground',
  );
}
